
GET http://localhost:3000/categories
###
GET http://localhost:3000/categories/1
###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 3"
}
###


PATCH http://localhost:3000/categories/3
Content-Type: application/json

{
    "name": "Category 3 updated"
}
###

DELETE http://localhost:3000/categories/2





###
GET http://localhost:3000/products
###
GET http://localhost:3000/products/12
###
POST http://localhost:3000/products
Content-Type: application/json

{
    # "name": "Product 1",
    # "price": 10000,
    # "categoryId": 3
}
###

PATCH http://localhost:3000/products/11
Content-Type: application/json

{
    "name": "Product 1 updated"
}
###
DELETE http://localhost:3000/products/2